version: "3.7"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped


  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: unless-stopped
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
      ports:
        - 9090:9090
      expose:
        - 9090
      networks:
        - monitoring 

  vader-exporter:
        image: ttl.sh/vader-temp:1h
        # build:
        #   context: ../../exporter
        #   dockerfile: ../../exporter/Dockerfile
        # container_name: vader-exporter
        expose:
          - 9093
        ports:
          - 9093:9093
        environment:
          - MQTTT_SERVER="mqtt:18003"
        networks:
          - monitoring
          - mqtt
  mock-publisher:
    image: ttl.sh/mock-temp:1h
    # build:
    #    context: ../../exporter/Testing  # Adjusted path to match the location of the Dockerfile
    #    dockerfile: ../../exporter/Testing/Dockerfile
    container_name: mock-publisher
    networks:
      - mqtt
    depends_on:
      - mqtt
  grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
      restart: unless-stopped
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana
      networks:
        - monitoring 

volumes:
  config:
  data:
  log:
  prometheus_data: {}
  grafana-data:

networks:
  mqtt:
  monitoring:
